theme: jekyll-theme-cayman
title: Alexey Mikhalkevich
description: <a href="http://vk.com/swaggyd"><img src="https://www.freeiconspng.com/uploads/vk-logo-png-1.png" border="0" height="160" width="160"></a>
