theme: jekyll-theme-cayman
title: Alexey Mikhalkevich
description: <a href="https://www.codewars.com/users/dopelord24"><img src="https://www.theindianwire.com/wp-content/uploads/2018/06/codewars-logo-1.png" border="0" height="100" width="100"></a> <a href="https://github.com/dopelord24"><img src="http://www.mukeshkumar.net/Upload/ArticleHeader/Header/github.jpeg" border="0" height="100" width="100"></a>
